name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and run Docker container
      shell: 'script -q -e -c "bash {0}"'
      run: docker build -t fastq -f Dockerfile .

    - name: Run unit tests
      run: docker run -i -w /tool fastq pytest tests/unit_tests/

    - name: Run integration tests
      run: docker run -i -w /tool fastq pytest tests/integration_tests/

