name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-clean-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and run Docker container
    - shell: 'script -q -e -c "bash {0}"'
      run: bash start_dev_docker.sh

    - name: Run black code cleanup
      run: black .

    - name: Run unit tests
      run: pytest tests/unit_test/

