name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-clean-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and run Docker container
      run: docker build -t fastq -f Dockerfile .

    - name: Run unit tests
      run: docker run -it -w /tool fastq pytest tests/unit_test/

